version: 1

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: tdcli
    main: ./cmd/tdcli
    binary: tdcli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: tdcli
    builds:
      - tdcli
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - '^style:'
      - Merge pull request
      - Merge branch
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999

release:
  github:
    owner: treasuredata
    name: treasuredata-go-sdk
  name_template: "{{.ProjectName}} v{{.Version}}"
  header: |
    ## Treasure Data Go SDK CLI v{{ .Version }}

    ### Installation

    #### Download binaries
    Download the appropriate binary for your platform from the assets below.

    #### Install via Go
    ```bash
    go install github.com/treasuredata/treasuredata-go-sdk/cmd/tdcli@{{ .Tag }}
    ```

    #### Install via Homebrew (macOS/Linux)
    ```bash
    brew install treasuredata/tap/tdcli
    ```

brews:
  - name: tdcli
    repository:
      owner: treasuredata
      name: homebrew-tap
    folder: Formula
    homepage: https://github.com/treasuredata/treasuredata-go-sdk
    description: "Command line interface for Treasure Data"
    license: "Apache-2.0"
    test: |
      system "#{bin}/tdcli", "--version"

winget:
  - name: tdcli
    publisher: TreasureData
    license: Apache-2.0
    homepage: https://github.com/treasuredata/treasuredata-go-sdk
    short_description: "Command line interface for Treasure Data"
    repository:
      owner: treasuredata
      name: winget-pkgs
      branch: "{{.ProjectName}}-{{.Version}}"
      pull_request:
        enabled: true
        draft: true
        base:
          owner: microsoft
          name: winget-pkgs
          branch: master

dockers:
  - image_templates:
      - "ghcr.io/treasuredata/tdcli:{{ .Version }}-amd64"
      - "ghcr.io/treasuredata/tdcli:latest-amd64"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"

  - image_templates:
      - "ghcr.io/treasuredata/tdcli:{{ .Version }}-arm64"
      - "ghcr.io/treasuredata/tdcli:latest-arm64"
    dockerfile: Dockerfile
    use: buildx
    goarch: arm64
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"

docker_manifests:
  - name_template: "ghcr.io/treasuredata/tdcli:{{ .Version }}"
    image_templates:
      - "ghcr.io/treasuredata/tdcli:{{ .Version }}-amd64"
      - "ghcr.io/treasuredata/tdcli:{{ .Version }}-arm64"
  - name_template: "ghcr.io/treasuredata/tdcli:latest"
    image_templates:
      - "ghcr.io/treasuredata/tdcli:latest-amd64"
      - "ghcr.io/treasuredata/tdcli:latest-arm64"