version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: tdcli
    main: ./cmd/tdcli
    binary: tdcli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: tdcli
    builds:
      - tdcli
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - '^style:'
      - Merge pull request
      - Merge branch
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999

release:
  github:
    owner: mickeey2525
    name: treasuredata-go-sdk
  name_template: "{{.ProjectName}} v{{.Version}}"
  header: |
    ## Treasure Data Go SDK CLI v{{ .Version }}

    ### Installation

    #### Download binaries
    Download the appropriate binary for your platform from the assets below.

    #### Install via Go
    ```bash
    go install github.com/mickeey2525/treasuredata-go-sdk/cmd/tdcli@{{ .Tag }}
    ```

dockers:
  - image_templates:
      - "ghcr.io/mickeey2525/tdcli:{{ .Version }}-amd64"
      - "ghcr.io/mickeey2525/tdcli:latest-amd64"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"

  - image_templates:
      - "ghcr.io/mickeey2525/tdcli:{{ .Version }}-arm64"
      - "ghcr.io/mickeey2525/tdcli:latest-arm64"
    dockerfile: Dockerfile
    use: buildx
    goarch: arm64
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"

docker_manifests:
  - name_template: "ghcr.io/mickeey2525/tdcli:{{ .Version }}"
    image_templates:
      - "ghcr.io/mickeey2525/tdcli:{{ .Version }}-amd64"
      - "ghcr.io/mickeey2525/tdcli:{{ .Version }}-arm64"
  - name_template: "ghcr.io/mickeey2525/tdcli:latest"
    image_templates:
      - "ghcr.io/mickeey2525/tdcli:latest-amd64"
      - "ghcr.io/mickeey2525/tdcli:latest-arm64"